service: serverless-settings-service
useDotenv: true
variablesResolutionMode: 20210219

plugins:
  - serverless-offline
  - serverless-deployment-bucket
  - serverless-esm-layer
  - serverless-plugin-aws-alerts
  - serverless-plugin-monorepo

provider:
  name: aws
  runtime: nodejs18.x
  architecture: arm64
  stage: ${opt:stage}
  region: ${env:REGION}
  versionFunctions: false
  memorySize: 128
  timeout: 5
  tracing:
    lambda: true
  logRetentionInDays: 14
  lambdaHashingVersion: 20201221
  environment:
    STAGE: ${opt:stage}
    REGION: ${env:REGION}
    NODE_ENV: ${env:NODE_ENV}
    DEPLOYMENT_BUCKET: ${env:DEPLOYMENT_BUCKET}
    SETTINGS_BUCKET: ${env:SETTINGS_BUCKET}
    SETTINGS_FILE: ${env:SETTINGS_FILE}
  deploymentBucket:
    name: ${env:DEPLOYMENT_BUCKET}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: arn:aws:logs:*:*:*
        - Effect: Allow
          Action:
            - s3:GetObject
          Resource:
            - arn:aws:s3:::${env:SETTINGS_BUCKET}
            - arn:aws:s3:::${env:SETTINGS_BUCKET}/*
        - Effect: Allow
          Action:
            - xray:PutTraceSegments
            - xray:PutTelemetryRecords
          Resource: '*'

package:
  excludeDevDependencies: true
  patterns:
    - package.json
    - dist/**
    - '!.*'
    - '!node_modules'
    - '!__tests__/**'
    - '!src/**'
    - '!static/**'
    - '!*.sh'
    - '!*config*'
    - '!coverage'
    - '!package-lock.json'
    - '.build'

custom:
  alerts:
    stages: # Optionally - select which stages to deploy alarms to
      - ${opt:stage}
    dashboards: true
    nameTemplate: $[functionName]-$[metricName]-Alarm # Optionally - naming template for alarms, can be overwritten in definitions
    prefixTemplate: $[stackName] # Optionally - override the alarm name prefix
    topics:
      alarm: arn:aws:sns:${aws:region}:${aws:accountId}:Default_CloudWatch_Alarms_Topic
    alarms:
      - functionThrottles
      - functionErrors
      - functionInvocations
      - functionDuration

layers:
  HermesSettingsNodeModules:
    path: ../../serverless-layer
    compatibleRuntimes:
      - nodejs18.x

functions:
  getSettings:
    handler: dist/handler.getSettingsHandler
    layers:
      - { Ref: HermesSettingsNodeModulesLambdaLayer }